version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: terra_db
      POSTGRES_USER: terra_user
      POSTGRES_PASSWORD: terra_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
